### ISSUE TITLE
Package not found in NPM registry

### ISSUE THREAD

**Issue by ramsrib** [portablemind/grapesjs-code-editor#1]
Running `npm i grapesjs-code-editor` fails with 404 error. This package is not found in the npmjs registry. Please fix it.

Refer: https://www.npmjs.com/search?q=grapesjs-code-editor

**Comment by dsgh** [comment]
Hi @ramsrib, I had forgotten to upload it to the npm registry. It is now uploaded, and the README was also updated accordingly, as the command should be: `npm i @truenorthtechnology/grapesjs-code-editor`

Let me know if you still find any issue! Thanks
